// src/utils/countries.ts
export const europeanCountries = [
    { code: 'AT', name: 'Austria' },
    { code: 'BE', name: 'Belgio' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'HR', name: 'Croazia' },
    { code: 'CY', name: 'Cipro' },
    { code: 'CZ', name: 'Repubblica Ceca' },
    { code: 'DK', name: 'Danimarca' },
    { code: 'EE', name: 'Estonia' },
    { code: 'FI', name: 'Finlandia' },
    { code: 'FR', name: 'Francia' },
    { code: 'DE', name: 'Germania' },
    { code: 'GR', name: 'Grecia' },
    { code: 'HU', name: 'Ungheria' },
    { code: 'IE', name: 'Irlanda' },
    { code: 'IT', name: 'Italia' },
    { code: 'LV', name: 'Lettonia' },
    { code: 'LT', name: 'Lituania' },
    { code: 'LU', name: 'Lussemburgo' },
    { code: 'MT', name: 'Malta' },
    { code: 'NL', name: 'Paesi Bassi' },
    { code: 'PL', name: 'Polonia' },
    { code: 'PT', name: 'Portogallo' },
    { code: 'RO', name: 'Romania' },
    { code: 'SK', name: 'Slovacchia' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'ES', name: 'Spagna' },
    { code: 'SE', name: 'Svezia' },
    { code: 'GB', name: 'Regno Unito' },
    { code: 'NO', name: 'Norvegia' },
    { code: 'IS', name: 'Islanda' },
];
